name: CI
on:
  pull_request:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      BLEND: ${{matrix.blend}}
    name: Test on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}} ${{matrix.blend && format('/ Blend {0}', matrix.blend)}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.17'
            otp: '27.2.2'
          - elixir: '1.17'
            otp: '27.2.2'
            blend: plug_crypto_1
          - elixir: '1.16'
            otp: '26.2.5.8'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache code and deps
        uses: actions/cache@v4
        with:
          path: |
            blend/*/_build
            blend/*/deps
            _build
            deps
          key: ${{runner.os}}-${{matrix.elixir}}-${{matrix.otp}}-${{matrix.blend}}-${{matrix.blend && hashFiles(format('blend/{0}/mix.lock', matrix.blend)) || hashFiles('mix.lock')}}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix compile
      - run: mix test
